# Tomcat
server:
  port: 8081
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/json,application/xml,application/octet-stream,text/html,text/xml,text/plain,text/css,text/javascript
# mysql
spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://43.143.5.156:13306/fcs?useUnicode=true&characterEncoding=UTF-8&allowLoadLocalInfile=true
    username : root
    password : root123
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  session:
    store-type: none
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
# netty配置
#netty:
#  boss: 1
#  worker: 4
#  timeout: 6000
#  port: 25207
#  portSalve: 7001
#  host: 1zr5986076.iok.la

netty:
  boss: 1
  worker: 4
  timeout: 6000
  port: 7000
  portSalve: 7001
  host: 127.0.0.1